//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_BAOCAOMATDOSUDUNG
    {
        public int MaBCCTMatDoSuDung { get; set; }
        public int MaPhong { get; set; }
        public int MaBCMatDoSuDung { get; set; }
        public Nullable<int> SoNgayThue { get; set; }
        public string TiLe { get; set; }
    
        public virtual BAOCAO_MATDOSUDUNGPHONG BAOCAO_MATDOSUDUNGPHONG { get; set; }
    }
}
