//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAM_SO
    {
        public int SoKhachToiDa { get; set; }
        public double PhuThu { get; set; }
        public double HeSo { get; set; }
        public Nullable<int> SoNgayThue { get; set; }
        public Nullable<int> PhuThuKhachThu { get; set; }
        public Nullable<int> SLKhachNuocNgoai { get; set; }
    }
}
