//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAO_DOANHTHUTHEOLOAIPHONG
    {
        public BAOCAO_DOANHTHUTHEOLOAIPHONG()
        {
            this.CHITIET_BAOCAODOANHTHU = new HashSet<CHITIET_BAOCAODOANHTHU>();
        }
    
        public int MaBCDoanhThu { get; set; }
        public int ThangBaoCao { get; set; }
    
        public virtual ICollection<CHITIET_BAOCAODOANHTHU> CHITIET_BAOCAODOANHTHU { get; set; }
    }
}
