//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAO_MATDOSUDUNGPHONG
    {
        public BAOCAO_MATDOSUDUNGPHONG()
        {
            this.CHITIET_BAOCAOMATDOSUDUNG = new HashSet<CHITIET_BAOCAOMATDOSUDUNG>();
        }
    
        public int MaBCMatDoSuDung { get; set; }
        public int ThangBaoCao { get; set; }
    
        public virtual ICollection<CHITIET_BAOCAOMATDOSUDUNG> CHITIET_BAOCAOMATDOSUDUNG { get; set; }
    }
}
