//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICH_VU
    {
        public DICH_VU()
        {
            this.DANG_KI_DICH_VU = new HashSet<DANG_KI_DICH_VU>();
        }
    
        public int MaDichVu { get; set; }
        public string TenDichVu { get; set; }
        public string DonViTinh { get; set; }
        public decimal DonGia { get; set; }
    
        public virtual ICollection<DANG_KI_DICH_VU> DANG_KI_DICH_VU { get; set; }
    }
}
