//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAI_PHONG
    {
        public LOAI_PHONG()
        {
            this.PHONGs = new HashSet<PHONG>();
        }
    
        public string MaLoaiPhong { get; set; }
        public string TenLoaiPhong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual ICollection<PHONG> PHONGs { get; set; }
    }
}
