//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAI_KHACH_HANG
    {
        public LOAI_KHACH_HANG()
        {
            this.KHACH_HANG = new HashSet<KHACH_HANG>();
        }
    
        public string MaLoaiKhach { get; set; }
        public string TenLoaiKhach { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<KHACH_HANG> KHACH_HANG { get; set; }
    }
}
