//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DATA_QUAN_LY_KHACH_SANEntities : DbContext
    {
        public DATA_QUAN_LY_KHACH_SANEntities()
            : base("name=DATA_QUAN_LY_KHACH_SANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BAOCAO_DOANHTHUTHEOLOAIPHONG> BAOCAO_DOANHTHUTHEOLOAIPHONG { get; set; }
        public DbSet<CHI_TIET_HOA_DON> CHI_TIET_HOA_DON { get; set; }
        public DbSet<CHI_TIET_PHIEU_THUE> CHI_TIET_PHIEU_THUE { get; set; }
        public DbSet<CHITIET_BAOCAODOANHTHU> CHITIET_BAOCAODOANHTHU { get; set; }
        public DbSet<DICH_VU> DICH_VU { get; set; }
        public DbSet<HOA_DON> HOA_DON { get; set; }
        public DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public DbSet<LOAI_KHACH_HANG> LOAI_KHACH_HANG { get; set; }
        public DbSet<LOAI_PHONG> LOAI_PHONG { get; set; }
        public DbSet<PHIEU_THUE_PHONG> PHIEU_THUE_PHONG { get; set; }
        public DbSet<PHONG> PHONGs { get; set; }
        public DbSet<THAM_SO> THAM_SO { get; set; }
    
        public virtual int spSuaThongTinPhong(Nullable<int> maPhong, string tinhTrang, string maLoaiPhong, string ghiChu)
        {
            var maPhongParameter = maPhong.HasValue ?
                new ObjectParameter("MaPhong", maPhong) :
                new ObjectParameter("MaPhong", typeof(int));
    
            var tinhTrangParameter = tinhTrang != null ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(string));
    
            var maLoaiPhongParameter = maLoaiPhong != null ?
                new ObjectParameter("MaLoaiPhong", maLoaiPhong) :
                new ObjectParameter("MaLoaiPhong", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSuaThongTinPhong", maPhongParameter, tinhTrangParameter, maLoaiPhongParameter, ghiChuParameter);
        }
    
        public virtual int spThemPhong(string tinhTrang, string maLoaiPhong, string ghiChu)
        {
            var tinhTrangParameter = tinhTrang != null ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(string));
    
            var maLoaiPhongParameter = maLoaiPhong != null ?
                new ObjectParameter("MaLoaiPhong", maLoaiPhong) :
                new ObjectParameter("MaLoaiPhong", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spThemPhong", tinhTrangParameter, maLoaiPhongParameter, ghiChuParameter);
        }
    
        public virtual int spXoaPhong(Nullable<int> maPhong)
        {
            var maPhongParameter = maPhong.HasValue ?
                new ObjectParameter("MaPhong", maPhong) :
                new ObjectParameter("MaPhong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spXoaPhong", maPhongParameter);
        }
    }
}
