//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUE_DICH_VU
    {
        public int MaDichVu { get; set; }
        public int MaKhachHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> PhiDichVu { get; set; }
    
        public virtual DICH_VU DICH_VU { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
